module.exports=(sequelize,D)=>sequelize.define('Product',{
id:{type:D.UUID,defaultValue:D.UUIDV4,primaryKey:true},
companyId:{type:D.UUID,allowNull:false},
categoryId:{type:D.UUID},
name:{type:D.STRING(220),allowNull:false},
slug:{type:D.STRING(240),allowNull:false,unique:true},
description:{type:D.TEXT},
sku:{type:D.STRING(80),unique:true},
price:{type:D.DECIMAL(12,2),allowNull:false},
compareAtPrice:{type:D.DECIMAL(12,2)},
currency:{type:D.STRING(3),defaultValue:'ETB'},
stock:{type:D.INTEGER,defaultValue:0},
imageUrl:{type:D.STRING(500)},
gallery:{type:D.JSON},
attributes:{type:D.JSON},
specifications:{type:D.JSON},
status:{type:D.ENUM('draft','active','archived'),defaultValue:'draft'},
affiliateEnabled:{type:D.BOOLEAN,defaultValue:true}
},{tableName:'products',indexes:[{fields:['company_id']},{fields:['category_id']},{fields:['status']}]});