<script setup>
import {ref,onMounted} from 'vue';import {RouterLink} from 'vue-router';import api from '../../services/api';import {addToCart} from '../../stores';import LoadingState from '../../components/ui/LoadingState.vue'
const products=ref([]),categories=ref([]),loading=ref(true),category=ref(''),search=ref('')
async function load(){loading.value=true;try{const [p,c]=await Promise.all([api.get('/products',{params:{search:search.value,categoryId:category.value||undefined}}),api.get('/categories')]);products.value=p.data.products||p.data;categories.value=c.data.categories||c.data}catch(e){}finally{loading.value=false}}
onMounted(load)
</script>
<template><section>
<div class="overflow-hidden rounded-3xl bg-slate-950 px-6 py-12 text-white md:px-12"><p class="text-sm font-bold uppercase tracking-[.2em] text-indigo-300">One company · endless choice</p><h1 class="mt-3 max-w-2xl text-4xl font-black tracking-tight md:text-6xl">Shop products. Share links. Earn commissions.</h1><p class="mt-5 max-w-xl text-slate-300">A focused commerce experience with categories, fast checkout and a built-in affiliate program.</p></div>
<div class="mt-8 flex flex-col gap-3 md:flex-row"><input v-model="search" @keyup.enter="load" placeholder="Search products…" class="flex-1 rounded-xl border bg-white px-4 py-3 outline-none focus:border-indigo-500"/><select v-model="category" @change="load" class="rounded-xl border bg-white px-4 py-3"><option value="">All categories</option><option v-for="c in categories" :key="c.id" :value="c.id">{{c.name}}</option></select></div>
<LoadingState v-if="loading"/><div v-else class="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><article v-for="p in products" :key="p.id" class="group overflow-hidden rounded-2xl border bg-white shadow-sm"><RouterLink :to="'/products/'+p.slug"><div class="aspect-square bg-slate-100"><img v-if="p.imageUrl" :src="p.imageUrl" class="h-full w-full object-cover transition group-hover:scale-105"/><div v-else class="flex h-full items-center justify-center text-slate-300">No image</div></div><div class="p-4"><h2 class="font-bold">{{p.name}}</h2><p class="mt-2 text-lg font-black text-indigo-600">{{Number(p.price).toLocaleString()}} {{p.currency||'ETB'}}</p></div></RouterLink><div class="px-4 pb-4"><button @click="addToCart(p)" class="w-full rounded-xl bg-slate-950 py-2.5 text-sm font-bold text-white hover:bg-indigo-700">Add to cart</button></div></article></div></section></template>