module.exports=(sequelize,D)=>sequelize.define('ShopMember',{
id:{type:D.UUID,defaultValue:D.UUIDV4,primaryKey:true},
shopId:{type:D.UUID,allowNull:false},
userId:{type:D.UUID,allowNull:false},
role:{type:D.ENUM('manager','catalog_manager','order_manager','affiliate_manager','finance_manager','staff'),defaultValue:'staff'},
status:{type:D.ENUM('invited','active','suspended','removed'),defaultValue:'invited'},
invitedAt:{type:D.DATE},
joinedAt:{type:D.DATE},
permissions:{type:D.JSON}
},{tableName:'shop_members',indexes:[{unique:true,fields:['shop_id','user_id']},{fields:['shop_id','status']}]});