module.exports=(sequelize,D)=>sequelize.define('Shop',{
id:{type:D.UUID,defaultValue:D.UUIDV4,primaryKey:true},
sellerId:{type:D.UUID,allowNull:false},
name:{type:D.STRING(160),allowNull:false},
slug:{type:D.STRING(180),allowNull:false,unique:true},
description:{type:D.TEXT},
logoUrl:{type:D.STRING(500)},
bannerUrl:{type:D.STRING(500)},
websiteUrl:{type:D.STRING(500)},
phone:{type:D.STRING(40)},
email:{type:D.STRING(190)},
country:{type:D.STRING(100)},
city:{type:D.STRING(100)},
status:{type:D.ENUM('pending','active','suspended','closed'),defaultValue:'pending'},
commissionEnabled:{type:D.BOOLEAN,defaultValue:true},
isVerified:{type:D.BOOLEAN,defaultValue:false},
settings:{type:D.JSON}
},{tableName:'shops',indexes:[{fields:['seller_id']},{fields:['status']}]});